import type {
  PaperExecutionAttemptResponse,
  PaperExecutionFillResponse,
  PaperExecutionOrderCommandResponse,
  PaperExecutionOrderViewResponse,
  PaperExecutionReconciliationResponse,
  PaperExecutionStepCommandResponse,
} from "@/lib/api-client";
import { raw } from "@/test/strategy-order-fixtures";

const digest = (character: string) => character.repeat(64);

export const executionRaw = {
  orderId: `peo_${digest("a")}`,
  orderDigest: digest("a"),
  attemptId: `pea_${digest("b")}`,
  attemptDigest: digest("b"),
  fillId: `pef_${digest("c")}`,
  fillDigest: digest("c"),
  settlementId: `pes_${digest("d")}`,
  requestId: "request-s213-exact",
  cursor: "opaque+/=cursor:下一页",
} as const;

const orderReference = {
  schema_version: 1,
  execution_order_id: executionRaw.orderId,
  execution_order_digest: executionRaw.orderDigest,
} as const;

const policyReference = {
  schema_version: 1,
  policy_id: "paper_execution_v1",
  max_fill_quantity_per_trade_event: "3.2500",
  slippage_bps: "1.2500",
  commission_bps: "2.5000",
  fee_bps: "0.1250",
  buy_tax_bps: "0.0000",
  sell_tax_bps: "1.7500",
  execution_price_policy_id: "consumed_trade_event_price_v1",
  slippage_policy_id: "fixed_bps_slippage_v1",
  transaction_cost_policy_id: "per_fill_bps_costs_v1",
  configuration_digest: digest("e"),
  reference_digest: digest("f"),
} as const;

const riskPolicyReference = {
  schema_version: 1,
  policy_id: "long_only_cash_risk_v1",
  reference_price_policy_id: "latest_trade_price_v1",
  maximum_order_quantity: "200",
  maximum_order_notional: "2000",
  configuration_digest: digest("1"),
  reference_digest: digest("2"),
} as const;

export const executionOrderView = {
  order: {
    schema_version: 1,
    execution_order_id: executionRaw.orderId,
    execution_order_digest: executionRaw.orderDigest,
    order_intent_reference: {
      schema_version: 1,
      intent_id: raw.intentId,
      intent_digest: raw.intentDigest,
    },
    risk_handoff_reference: {
      schema_version: 1,
      order_intent_reference: {
        schema_version: 1,
        intent_id: raw.intentId,
        intent_digest: raw.intentDigest,
      },
      risk_decision_id: raw.decisionId,
      risk_decision_digest: raw.decisionDigest,
      risk_snapshot_id: raw.snapshotId,
      risk_snapshot_digest: raw.snapshotDigest,
      risk_policy_reference: riskPolicyReference,
      outcome: "allow",
      reference_digest: digest("3"),
    },
    account_handoff_reference: {
      schema_version: 1,
      account_id: raw.accountId,
      account_head_version: 1,
      account_head_event_id: raw.accountEventId,
      account_head_chain_digest: raw.accountChainDigest,
      lifecycle_status: "active",
      base_currency: "USD",
      cash_balance: "1000.00000000",
      available_cash: "1000.00000000",
      instrument_id: raw.instrumentId,
      current_instrument_quantity: "0.000000000000",
      reference_digest: digest("4"),
    },
    market_handoff_reference: {
      schema_version: 1,
      calendar_id: raw.calendarId,
      calendar_version: 1,
      trading_session_id: raw.sessionId,
      trading_date: "2026-08-11",
      session_type: "regular",
      session_open_time: "2026-08-11T01:30:00Z",
      session_close_time: "2026-08-11T08:00:00Z",
      replay_id: raw.replayId,
      event_stream_digest: raw.streamDigest,
      cursor_position: 2,
      last_event_id: raw.eventId,
      current_event_id: raw.eventId,
      current_event_time: raw.eventTime,
      instrument_id: raw.instrumentId,
      handoff_replay_status: "running",
      reference_digest: digest("5"),
    },
    execution_policy_reference: policyReference,
    account_id: raw.accountId,
    instrument_id: raw.instrumentId,
    side: "buy",
    requested_quantity: "10.2300",
    origin_command_digest: digest("6"),
    origin_actor: "founder",
    created_at: "2026-08-11T02:00:00Z",
  },
  state: {
    schema_version: 1,
    execution_order_reference: orderReference,
    execution_version: 0,
    status: "working",
    requested_quantity: "10.2300",
    cumulative_filled_quantity: "0.0000",
    remaining_quantity: "10.2300",
    terminal: false,
  },
} as const satisfies PaperExecutionOrderViewResponse;

const eventReference = {
  schema_version: 1,
  replay_id: raw.replayId,
  event_stream_digest: raw.streamDigest,
  event_id: "market-event-3",
  event_digest: digest("7"),
  event_type: "trade",
  event_time: "2026-08-11T01:32:00Z",
  instrument_id: raw.instrumentId,
  consumed_event_position: 3,
  pre_step_cursor_position: 2,
  post_step_cursor_position: 3,
  post_step_last_event_id: "market-event-3",
  post_step_current_event_time: "2026-08-11T01:32:00Z",
  post_step_replay_status: "running",
  reference_digest: digest("8"),
} as const;

const priceEvidence = {
  schema_version: 1,
  execution_price_policy_id: "consumed_trade_event_price_v1",
  slippage_policy_id: "fixed_bps_slippage_v1",
  execution_event_reference: eventReference,
  side: "buy",
  base_trade_price: "12.34000000",
  slippage_bps: "1.2500",
  pre_round_execution_price: "12.341542500000",
  execution_price: "12.34154250",
  rounding_quantum: "0.00000001",
  rounding_mode: "ROUND_HALF_EVEN",
  rounding_applied: true,
  price_evidence_digest: digest("9"),
} as const;

const costEvidence = {
  schema_version: 1,
  transaction_cost_policy_id: "per_fill_bps_costs_v1",
  execution_price_evidence: priceEvidence,
  fill_quantity: "3.2500",
  rounding_quantum: "0.00000001",
  rounding_mode: "ROUND_HALF_EVEN",
  gross_notional_pre_round: "40.109013125000",
  gross_notional: "40.10901312",
  gross_notional_rounding_applied: true,
  commission_bps: "2.5000",
  commission_pre_round: "0.010027253280",
  commission: "0.01002725",
  commission_rounding_applied: true,
  fee_bps: "0.1250",
  fee_pre_round: "0.000501362664",
  fee: "0.00050136",
  fee_rounding_applied: true,
  side_tax_bps: "0.0000",
  tax_pre_round: "0.000000000000",
  tax: "0.00000000",
  tax_rounding_applied: false,
  total_charges: "0.01052861",
  cost_evidence_digest: digest("0"),
} as const;

export const executionAttempt = {
  schema_version: 1,
  attempt_id: executionRaw.attemptId,
  attempt_digest: executionRaw.attemptDigest,
  execution_order_reference: orderReference,
  execution_version_before: 0,
  execution_version_after: 1,
  attempt_result: "fill",
  no_fill_reason_code: null,
  terminal_reason_code: null,
  pre_step_cursor: {
    schema_version: 1,
    replay_id: raw.replayId,
    event_stream_digest: raw.streamDigest,
    position: 2,
    last_event_id: raw.eventId,
    current_event_time: raw.eventTime,
    status: "running",
  },
  post_step_cursor: {
    schema_version: 1,
    replay_id: raw.replayId,
    event_stream_digest: raw.streamDigest,
    position: 3,
    last_event_id: "market-event-3",
    current_event_time: "2026-08-11T01:32:00Z",
    status: "running",
  },
  consumed_event_reference: eventReference,
  prior_order_state: executionOrderView.state,
  risk_revalidation: {
    schema_version: 1,
    risk_revalidation_id: `perr_${digest("a")}`,
    risk_revalidation_digest: digest("a"),
    execution_order_reference: orderReference,
    execution_version: 0,
    account_id: raw.accountId,
    account_head_version: 1,
    account_head_event_id: raw.accountEventId,
    account_head_chain_digest: raw.accountChainDigest,
    available_cash: "1000.00000000",
    current_instrument_quantity: "0.000000000000",
    requested_quantity: "10.2300",
    remaining_quantity_before_step: "10.2300",
    candidate_fill_quantity: "3.2500",
    execution_price_evidence: priceEvidence,
    cost_evidence: costEvidence,
    cumulative_filled_gross_notional: "0.00000000",
    projected_notional_pre_round: "126.253977775000",
    projected_order_gross_notional: "126.25397778",
    rounding_quantum: "0.00000001",
    rounding_mode: "ROUND_HALF_EVEN",
    projected_notional_rounding_applied: true,
    risk_policy_reference: riskPolicyReference,
    rules: [{ rule_id: "maximum_order_notional", observed_value: "126.25397778", limit_value: "2000", passed: true, reason_code: null }],
    outcome: "allow",
    reason_codes: [],
  },
  created_at: "2026-08-11T02:01:00Z",
} as const satisfies PaperExecutionAttemptResponse;

export const executionFill = {
  schema_version: 1,
  fill_id: executionRaw.fillId,
  fill_digest: executionRaw.fillDigest,
  execution_order_reference: orderReference,
  attempt_reference: { schema_version: 1, attempt_id: executionRaw.attemptId, attempt_digest: executionRaw.attemptDigest },
  execution_event_reference: eventReference,
  side: "buy",
  fill_quantity: "3.2500",
  execution_price_evidence: priceEvidence,
  cost_evidence: costEvidence,
  created_at: "2026-08-11T02:01:00Z",
} as const satisfies PaperExecutionFillResponse;

export const settlementLink = {
  schema_version: 1,
  settlement_link_id: executionRaw.settlementId,
  settlement_link_digest: digest("d"),
  settlement_link_evidence_digest: digest("e"),
  execution_order_reference: orderReference,
  execution_attempt_reference: { schema_version: 1, attempt_id: executionRaw.attemptId, attempt_digest: executionRaw.attemptDigest },
  execution_fill_reference: { schema_version: 1, fill_id: executionRaw.fillId, fill_digest: executionRaw.fillDigest },
  account_id: raw.accountId,
  account_event_id: "account-event-s213-fill",
  account_event_digest: digest("f"),
  account_chain_digest: digest("1"),
  account_version: 2,
  cash_entry_id: "cash-entry-s213-fill",
  cash_entry_digest: digest("2"),
  position_entry_id: "position-entry-s213-fill",
  position_entry_digest: digest("3"),
} as const;

export const executionOrderCommand = {
  schema_version: 1,
  replayed: false,
  request_id: executionRaw.requestId,
  result: executionOrderView,
} as const satisfies PaperExecutionOrderCommandResponse;

export const executionStepCommand = {
  schema_version: 1,
  replayed: false,
  request_id: executionRaw.requestId,
  result: {
    schema_version: 1,
    attempt: executionAttempt,
    fill: executionFill,
    settlement_link: settlementLink,
    account_event_id: settlementLink.account_event_id,
    order_state: {
      ...executionOrderView.state,
      execution_version: 1,
      status: "partially_filled",
      cumulative_filled_quantity: "3.2500",
      remaining_quantity: "6.9800",
    },
  },
} as const satisfies PaperExecutionStepCommandResponse;

export const executionReconciliation = {
  schema_version: 1,
  order: executionOrderView.order,
  state: executionStepCommand.result.order_state,
  attempts: [executionAttempt],
  fills: [executionFill],
  settlement_links: [settlementLink],
} as const satisfies PaperExecutionReconciliationResponse;
