import type {
  PortfolioReviewDetailResponse,
  PortfolioReviewListResponse,
} from "@/lib/api-client";

const sourceDigest = "source-digest-" + "a".repeat(64);
const baselineDigest = "baseline-digest-" + "b".repeat(64);
const proposedDigest = "proposed-digest-" + "c".repeat(64);
const analysisDigest = "analysis-digest-" + "d".repeat(64);

export const portfolioReviewRecord: PortfolioReviewListResponse[number] = {
  record_schema_version: 1,
  review_id: "synthetic-review-175",
  status: "awaiting_decision",
  source_schema_version: 1,
  source_id: "synthetic-source-175",
  source_digest: sourceDigest,
  baseline_scenario_id: "synthetic-baseline",
  baseline_scenario_digest: baselineDigest,
  proposed_scenario_id: "synthetic-proposed",
  proposed_scenario_digest: proposedDigest,
  proposed_component_id: "component-b",
  analysis_schema_version: 1,
  analysis_digest: analysisDigest,
  created_by: "synthetic-founder",
  created_timestamp: "2026-07-20T01:00:00Z",
  decision_schema_version: null,
  decision_id: null,
  decision_digest: null,
  outcome: null,
  reviewed_by: null,
  reviewed_timestamp: null,
  version: 1,
  updated_timestamp: "2026-07-20T01:00:00Z",
};

const baselineScenario = {
  schema_version: 1 as const,
  scenario_id: "synthetic-baseline",
  source_id: "synthetic-source-175",
  source_digest: sourceDigest,
  component_weights: [
    { component_id: "component-a", weight: 0.8750000000001 },
    { component_id: "component-b", weight: 0.1249999999999 },
  ],
  rationale: "Synthetic baseline rationale",
  assumptions: ["Synthetic baseline assumption", "Synthetic baseline assumption"],
  warnings: ["Synthetic baseline warning"],
  scenario_digest: baselineDigest,
};

const proposedScenario = {
  schema_version: 1 as const,
  scenario_id: "synthetic-proposed",
  source_id: "synthetic-source-175",
  source_digest: sourceDigest,
  component_weights: [
    { component_id: "component-a", weight: 0.3333333333333 },
    { component_id: "component-b", weight: 0.6666666666667 },
  ],
  rationale: "Synthetic proposed rationale",
  assumptions: ["Synthetic proposed assumption"],
  warnings: ["Synthetic proposed warning"],
  scenario_digest: proposedDigest,
  proposed_component_id: "component-b",
};

const baselineBehavior = {
  schema_version: 1 as const,
  scenario_id: "synthetic-baseline",
  scenario_digest: baselineDigest,
  observation_count: 3,
  evaluation_start_timestamp: "2026-01-01T00:00:00Z",
  evaluation_end_timestamp: "2026-01-03T00:00:00Z",
  periods_per_year: null,
  mean_return: 0.123456789012345,
  sample_volatility: 0.765432109876543,
  annualized_volatility: null,
  min_return: -0.222222222222222,
  max_return: 0.444444444444444,
  positive_periods: 1,
  negative_periods: 1,
  zero_periods: 1,
  loss_rate: 0.333333333333333,
  ending_equity: 1.23456789012345,
  cumulative_return: 0.23456789012345,
  worst_drawdown: {
    schema_version: 1 as const,
    max_drawdown: -0.135791357913579,
    peak_date: "2026-01-01T00:00:00Z",
    trough_date: "2026-01-02T00:00:00Z",
    recovery_date: null,
    recovered: false,
    duration_periods: 2,
    time_to_trough_periods: 1,
    time_to_recovery_periods: null,
  },
  component_contributions: [
    {
      schema_version: 1 as const,
      component_id: "component-a",
      strategy_id: "synthetic-strategy-a",
      weight: 0.8750000000001,
      total_contribution: 0.101010101010101,
      mean_contribution: 0.033670033670034,
      positive_periods: 1,
      negative_periods: 1,
      zero_periods: 1,
    },
    {
      schema_version: 1 as const,
      component_id: "component-b",
      strategy_id: "synthetic-strategy-b",
      weight: 0.1249999999999,
      total_contribution: -0.02020202020202,
      mean_contribution: -0.006734006734007,
      positive_periods: 1,
      negative_periods: 2,
      zero_periods: 0,
    },
  ],
};

const proposedBehavior = {
  ...baselineBehavior,
  scenario_id: "synthetic-proposed",
  scenario_digest: proposedDigest,
  mean_return: -0.987654321098765,
  sample_volatility: 0.246813579135792,
  min_return: -0.919191919191919,
  max_return: 0.818181818181818,
  positive_periods: 2,
  negative_periods: 1,
  zero_periods: 0,
  loss_rate: 0.111111111111111,
  ending_equity: 0.876543210987654,
  cumulative_return: -0.123456789012346,
  worst_drawdown: {
    ...baselineBehavior.worst_drawdown,
    max_drawdown: -0.975319753197532,
    recovery_date: "2026-01-03T00:00:00Z",
    recovered: true,
    time_to_recovery_periods: 1,
  },
  component_contributions: [
    {
      ...baselineBehavior.component_contributions[0],
      weight: 0.3333333333333,
      total_contribution: -0.303030303030303,
      mean_contribution: -0.101010101010101,
    },
    {
      ...baselineBehavior.component_contributions[1],
      weight: 0.6666666666667,
      total_contribution: 0.404040404040404,
      mean_contribution: 0.134680134680135,
    },
  ],
};

export const portfolioReviewDetail: PortfolioReviewDetailResponse = {
  record: portfolioReviewRecord,
  source: {
    schema_version: 1,
    source_id: "synthetic-source-175",
    components: [
      {
        schema_version: 1,
        component_id: "component-a",
        strategy_id: "synthetic-strategy-a",
        evidence_references: [{
          schema_version: 1,
          reference_type: "research_run",
          reference_id: "synthetic-run-a",
          label: "Synthetic A",
          description: null,
        }],
        symbols: ["SYN-A", "SYN-SHARED"],
        label: "Synthetic component A",
        description: "Synthetic only",
      },
      {
        schema_version: 1,
        component_id: "component-b",
        strategy_id: "synthetic-strategy-b",
        evidence_references: [{
          schema_version: 1,
          reference_type: "configured_run",
          reference_id: "synthetic-run-b",
          label: null,
          description: "Synthetic B",
        }],
        symbols: null,
        label: null,
        description: "Synthetic only",
      },
    ],
    return_observations: [
      { schema_version: 1, timestamp: "2026-01-01T00:00:00Z", component_returns: [0.111111111111111, -0.222222222222222] },
      { schema_version: 1, timestamp: "2026-01-02T00:00:00Z", component_returns: [0, 0.333333333333333] },
      { schema_version: 1, timestamp: "2026-01-03T00:00:00Z", component_returns: [-0.444444444444444, 0.555555555555555] },
    ],
    evaluation_frequency: "synthetic-daily",
    periods_per_year: null,
    created_by: "synthetic-founder",
    created_timestamp: "2026-07-20T00:30:00Z",
    assumptions: ["Synthetic source assumption", "Synthetic source assumption"],
    warnings: ["Synthetic source warning"],
    missing_evidence: ["Synthetic missing symbol evidence"],
    source_digest: sourceDigest,
  },
  analysis: {
    schema_version: 1,
    review_id: "synthetic-review-175",
    analysis_evidence_scope: "historical_scenario_evidence",
    source_id: "synthetic-source-175",
    source_digest: sourceDigest,
    component_ids: ["component-a", "component-b"],
    baseline_scenario_id: "synthetic-baseline",
    baseline_scenario_digest: baselineDigest,
    proposed_scenario_id: "synthetic-proposed",
    proposed_scenario_digest: proposedDigest,
    proposed_component_id: "component-b",
    baseline_scenario: baselineScenario,
    proposed_scenario: proposedScenario,
    concentration_exposure_analysis: {
      schema_version: 1,
      source_id: "synthetic-source-175",
      source_digest: sourceDigest,
      component_ids: ["component-a", "component-b"],
      baseline_concentration: {
        schema_version: 1,
        scenario_id: "synthetic-baseline",
        scenario_digest: baselineDigest,
        largest_component_id: "component-a",
        largest_component_weight: 0.8750000000001,
        top_3_weight: 1,
        herfindahl_hirschman_index: 0.78125000000015,
        effective_component_count: 1.27999999999975,
      },
      proposed_concentration: {
        schema_version: 1,
        scenario_id: "synthetic-proposed",
        scenario_digest: proposedDigest,
        largest_component_id: "component-b",
        largest_component_weight: 0.6666666666667,
        top_3_weight: 1,
        herfindahl_hirschman_index: 0.55555555555558,
        effective_component_count: 1.79999999999992,
      },
      component_exposures: [
        {
          schema_version: 1,
          component_id: "component-a",
          strategy_id: "synthetic-strategy-a",
          baseline_weight: 0.8750000000001,
          proposed_weight: 0.3333333333333,
          weight_delta: -0.5416666666668,
          change_type: "decreased",
          baseline_active: true,
          proposed_active: true,
          symbols: ["SYN-A", "SYN-SHARED"],
          symbol_evidence_status: "available",
        },
        {
          schema_version: 1,
          component_id: "component-b",
          strategy_id: "synthetic-strategy-b",
          baseline_weight: 0.1249999999999,
          proposed_weight: 0.6666666666667,
          weight_delta: 0.5416666666668,
          change_type: "increased",
          baseline_active: true,
          proposed_active: true,
          symbols: null,
          symbol_evidence_status: "missing",
        },
      ],
      baseline_universe_coverage: {
        schema_version: 1,
        scenario_id: "synthetic-baseline",
        scenario_digest: baselineDigest,
        components_with_symbol_evidence: ["component-a"],
        components_missing_symbol_evidence: ["component-b"],
        active_component_ids: ["component-a", "component-b"],
        active_components_with_symbol_evidence: ["component-a"],
        active_components_missing_symbol_evidence: ["component-b"],
        source_component_count: 2,
        components_with_symbol_evidence_count: 1,
        components_missing_symbol_evidence_count: 1,
        active_component_count: 2,
        active_components_with_symbol_evidence_count: 1,
        active_components_missing_symbol_evidence_count: 1,
        active_coverage_complete: false,
      },
      proposed_universe_coverage: {
        schema_version: 1,
        scenario_id: "synthetic-proposed",
        scenario_digest: proposedDigest,
        components_with_symbol_evidence: ["component-a"],
        components_missing_symbol_evidence: ["component-b"],
        active_component_ids: ["component-a", "component-b"],
        active_components_with_symbol_evidence: ["component-a"],
        active_components_missing_symbol_evidence: ["component-b"],
        source_component_count: 2,
        components_with_symbol_evidence_count: 1,
        components_missing_symbol_evidence_count: 1,
        active_component_count: 2,
        active_components_with_symbol_evidence_count: 1,
        active_components_missing_symbol_evidence_count: 1,
        active_coverage_complete: false,
      },
    },
    interaction_impact_analysis: {
      schema_version: 1,
      source_id: "synthetic-source-175",
      source_digest: sourceDigest,
      component_ids: ["component-a", "component-b"],
      proposed_component_id: "component-b",
      symbol_overlaps: [{
        schema_version: 1,
        left_component_id: "component-a",
        right_component_id: "component-b",
        status: "unavailable",
        unavailable_reason: "missing_symbol_evidence",
        missing_symbol_component_ids: ["component-b"],
        shared_symbols: null,
        shared_symbol_count: null,
        union_symbol_count: null,
        jaccard_overlap: null,
      }],
      pairwise_correlations: [{
        schema_version: 1,
        left_component_id: "component-a",
        right_component_id: "component-b",
        status: "unavailable",
        unavailable_reason: "zero_variance",
        zero_variance_series: ["component-b", "component-a"],
        correlation: null,
        observation_count: 3,
        evaluation_start_timestamp: "2026-01-01T00:00:00Z",
        evaluation_end_timestamp: "2026-01-03T00:00:00Z",
      }],
      candidate_baseline_correlation: {
        schema_version: 1,
        candidate_component_id: "component-b",
        candidate_baseline_weight: 0.1249999999999,
        baseline_scenario_id: "synthetic-baseline",
        baseline_scenario_digest: baselineDigest,
        status: "available",
        unavailable_reason: null,
        zero_variance_series: [],
        correlation: -0.24680246802468,
        observation_count: 3,
        evaluation_start_timestamp: "2026-01-01T00:00:00Z",
        evaluation_end_timestamp: "2026-01-03T00:00:00Z",
      },
      baseline_behavior: baselineBehavior,
      proposed_behavior: proposedBehavior,
      proposed_impact: {
        schema_version: 1,
        mean_return_delta: -1.11111111011111,
        sample_volatility_delta: -0.518618530740751,
        annualized_volatility_delta: null,
        min_return_delta: -0.696969696969697,
        max_return_delta: 0.373737373737374,
        positive_periods_delta: 1,
        negative_periods_delta: 0,
        zero_periods_delta: -1,
        loss_rate_delta: -0.222222222222222,
        ending_equity_delta: -0.358024679135796,
        cumulative_return_delta: -0.358024679135796,
        max_drawdown_delta: -0.839528395283953,
      },
      component_contribution_impacts: [
        {
          schema_version: 1,
          component_id: "component-a",
          strategy_id: "synthetic-strategy-a",
          baseline_weight: 0.8750000000001,
          proposed_weight: 0.3333333333333,
          total_contribution_delta: -0.404040404040404,
          mean_contribution_delta: -0.134680134680135,
          positive_periods_delta: 0,
          negative_periods_delta: 0,
          zero_periods_delta: 0,
        },
        {
          schema_version: 1,
          component_id: "component-b",
          strategy_id: "synthetic-strategy-b",
          baseline_weight: 0.1249999999999,
          proposed_weight: 0.6666666666667,
          total_contribution_delta: 0.424242424242424,
          mean_contribution_delta: 0.141414141414142,
          positive_periods_delta: 0,
          negative_periods_delta: 0,
          zero_periods_delta: 0,
        },
      ],
    },
    assumptions: ["Synthetic analysis assumption"],
    warnings: ["Synthetic analysis warning", "Synthetic analysis warning"],
    missing_evidence: ["Synthetic analysis missing evidence"],
    created_by: "synthetic-analyst",
    created_timestamp: "2026-07-20T01:00:00Z",
    analysis_digest: analysisDigest,
  },
  decision: null,
};

export const settledPortfolioReviewDetail: PortfolioReviewDetailResponse = {
  ...portfolioReviewDetail,
  record: {
    ...portfolioReviewRecord,
    status: "approved",
    decision_schema_version: 1,
    decision_id: "synthetic-decision-175",
    decision_digest: "decision-digest-" + "e".repeat(64),
    outcome: "approved",
    reviewed_by: "synthetic-reviewer",
    reviewed_timestamp: "2026-07-20T02:00:00Z",
    version: 2,
    updated_timestamp: "2026-07-20T02:00:00Z",
  },
  decision: {
    schema_version: 1,
    decision_id: "synthetic-decision-175",
    decision_scope: "portfolio_review_governance_only",
    review_id: "synthetic-review-175",
    analysis_digest: analysisDigest,
    source_id: "synthetic-source-175",
    source_digest: sourceDigest,
    baseline_scenario_id: "synthetic-baseline",
    baseline_scenario_digest: baselineDigest,
    proposed_scenario_id: "synthetic-proposed",
    proposed_scenario_digest: proposedDigest,
    outcome: "approved",
    rationale: "Synthetic governance rationale",
    reviewed_by: "synthetic-reviewer",
    reviewed_timestamp: "2026-07-20T02:00:00Z",
    notes: ["Synthetic note", "Synthetic note"],
    warnings: ["Synthetic decision warning"],
    decision_digest: "decision-digest-" + "e".repeat(64),
  },
};
